# Setup
title: "모두를 위한 컨벡스 최적화"
description: "모두를 위한 컨벡스 최적화"
url: https://convex-optimization-for-all.github.io
baseurl: ""
imgurl: https://convex-optimization-for-all.github.io/img
permalink: pretty

# About/contact
author:
  name: Kyeongmin Woo
  email: wgm0601@gmail.com

# Custom vars
version: 1.1.0
markdown: kramdown
