services:
  jekyll:
      image: jekyll/jekyll:4.2.0
      command: bash -c "gem install bundler:1.17.2 && jekyll serve --force_polling"
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll
