name: closed_issue

on:
  issues:
    types: [closed]

jobs:
  changeIssueTitle:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Change issue title
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_TITLE=$(gh issue view ${{ github.event.issue.number }} \
            --repo ${{ github.repository }} --json title \
            --jq '"[Closed] " + (.title | split("·")[0] | rtrimstr(" "))')

          gh issue edit ${{ github.event.issue.number }} \
            --repo ${{ github.repository }} --title "$NEW_TITLE"
